repos:
  # Elixir formatting
  - repo: https://github.com/pre-commit/mirrors-mix-format
    rev: v0.3.21
    hooks:
      - id: mix-format

  # Markdown formatting with prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(md|markdown)$
        types: [file]
